// The offline shell — the app has to work at a table with no signal, which is the
// normal case in a house, not an edge case. A PWA that installs and then shows a
// browser error page when the wifi drops is worse than no PWA: it looks installed
// and isn't.
//
// Two policies, deliberately different:
//   • tiles  — cache-first. They are generated by `npm run tiles` and never change
//              between builds, so the round trip is pure latency on the one path
//              that matters (a tile drawing while a table waits).
//   • shell  — network-first, cache as fallback. A fix pushed to Pages must reach
//              the phone on the next load, not on the next CACHE_VERSION bump.
//
// Every path here is RELATIVE (`./js/rules.js`, never `/js/rules.js`). On Pages the
// app is served from a repo subpath, where a root-absolute path 404s while working
// perfectly on localhost — and a precache list that 404s does not degrade, it fails
// the whole install, so a single wrong path means no offline at all, silently.
//
// `test/app.test.js` holds this file to the filesystem: every `./tiles/*.svg` on
// disk must be listed, every `src/app/js/*.js` must be listed, and nothing may be
// listed that does not exist. Add a tile or a module without a line here and
// `npm test` fails rather than the phone quietly missing it offline.

const CACHE_VERSION = "v1";
const CACHE = `skor-maciok-${CACHE_VERSION}`;

const SHELL = [
  "./",
  "./index.html",
  "./app.css",
  "./manifest.webmanifest",
  "./js/io.js",
  "./js/rules.js",
  "./js/settle.js",
  "./js/store.js",
  "./js/ui.js",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
];

// A service worker cannot enumerate a directory, so these are listed. The count is
// asserted by the test, not by this comment.
const TILES = [
  "./tiles/ban-1.svg", "./tiles/ban-2.svg", "./tiles/ban-3.svg",
  "./tiles/ban-4.svg", "./tiles/ban-5.svg", "./tiles/ban-6.svg",
  "./tiles/ban-7.svg", "./tiles/ban-8.svg", "./tiles/ban-9.svg",
  "./tiles/tong-1.svg", "./tiles/tong-2.svg", "./tiles/tong-3.svg",
  "./tiles/tong-4.svg", "./tiles/tong-5.svg", "./tiles/tong-6.svg",
  "./tiles/tong-7.svg", "./tiles/tong-8.svg", "./tiles/tong-9.svg",
  "./tiles/sok-1.svg", "./tiles/sok-2.svg", "./tiles/sok-3.svg",
  "./tiles/sok-4.svg", "./tiles/sok-5.svg", "./tiles/sok-6.svg",
  "./tiles/sok-7.svg", "./tiles/sok-8.svg", "./tiles/sok-9.svg",
  "./tiles/bunga-merah-1.svg", "./tiles/bunga-merah-2.svg",
  "./tiles/bunga-merah-3.svg", "./tiles/bunga-merah-4.svg",
  "./tiles/bunga-hitam-1.svg", "./tiles/bunga-hitam-2.svg",
  "./tiles/bunga-hitam-3.svg", "./tiles/bunga-hitam-4.svg",
  "./tiles/cung.svg", "./tiles/fat.svg", "./tiles/nan.svg",
  "./tiles/pai.svg", "./tiles/pei.svg", "./tiles/si.svg",
  "./tiles/tung.svg", "./tiles/kim-marker.svg",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // `addAll` is atomic: one bad path rejects the whole install. That is the
      // behaviour we want — an install that half-succeeded would report itself
      // offline-ready and then 404 the one tile it never fetched.
      await cache.addAll([...SHELL, ...TILES]);
      // Take over immediately: the page that registered this worker is already
      // open and already usable, and waiting for it to close would mean the first
      // session is the one session without offline.
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // Drop every earlier cache. A rebuild that changed `app.css` must not be
      // answered from the previous version's copy — that is how a fix ships and
      // nobody sees it.
      for (const key of await caches.keys()) {
        if (key !== CACHE) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

const isTile = (url) => url.pathname.includes("/tiles/");

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  let url;
  try {
    url = new URL(req.url);
  } catch {
    return;
  }
  // Same-origin only. There is nothing cross-origin to cache, and passing one
  // through would store an opaque response as if it were usable.
  if (url.origin !== self.location.origin) return;

  if (isTile(url)) {
    event.respondWith(
      (async () => {
        const hit = await caches.match(req);
        if (hit) return hit;
        const res = await fetch(req);
        if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
        return res;
      })(),
    );
    return;
  }

  event.respondWith(
    (async () => {
      // Navigations are stored under one normalised key (`./index.html`) rather
      // than under whatever URL was asked for, so the fallback below is found
      // whether the table opened `/`, `/index.html`, or a `/repo/` subpath.
      const key = req.mode === "navigate" ? "./index.html" : req;
      try {
        const res = await fetch(req);
        if (res.ok) (await caches.open(CACHE)).put(key, res.clone());
        return res;
      } catch {
        const hit = await caches.match(key);
        if (hit) return hit;
        if (req.mode === "navigate") {
          const shell = await caches.match("./index.html");
          if (shell) return shell;
        }
        throw new Error("offline dan tidak ada di cache");
      }
    })(),
  );
});
